name: Test
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - .github/**
      - package.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Test
        run: pnpm test
